# -*- coding: utf-8 -*-
"""Copy of Copy of Copy of Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z1l0UH-HgKYrawuCXvj8QZ3wp5i6UHDd
"""

import matplotlib.pyplot as plt
import numpy as np

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
x = np.linspace(0, 10, 100)

plt.plot(x, np.sin(x), '-')
plt.plot(x, np.cos(x), '--')
plt.xlabel('x ekseni')
plt.ylabel('y ekseni')
plt.legend(('sin', 'cos'))

fig = plt.figure()
x = np.arange(0,10,0.5)
y1 = x*x
y2 = x*x*x
fig, axes = plt.subplots(1,2)
axes[0].plot(x,y1,'g--o')
axes[1].plot(x,y2,'m--o')
fig.savefig('subplots.png')

fig.savefig('data.png')

import seaborn as sns 
import pandas as pd

iris = sns.load_dataset('iris') 
iris.head()

iris['petal_length'].plot(color='green')

sns.lineplot(data=iris, y='sepal_length', x=iris.index, hue ='species')

from numpy.random import seed
from numpy.random import randn
from matplotlib import pyplot
x = 20 * randn(1000) + 100
y = x + (10 * randn(1000) + 50)
pyplot.scatter(x,y)
pyplot.show( )

fig, ax = plt.subplots(figsize =(10,5))
ax.scatter(iris['sepal_length'], iris['sepal_width'])
ax.set_title('Irıs Dataset')
ax.set_xlabel('sepal_length')
ax.set_ylabel('sepal_width')

"""EXAMPLE

"""

import matplotlib.pyplot as plt
x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]
plt.scatter(x,y)
plt.xlabel('The Age Of Car')
plt.ylabel('The Speed Of Car')
plt.show()

iris.groupby(by='species').mean()['sepal_length']

data = iris.groupby(by='species').mean()['sepal_length']
ax = sns.barplot(x=data.index, y=data.values)
ax.set_title('Sepal Length Means')
ax.set_ylabel('Max')

sns.histplot(color='aqua', data=iris, x='sepal_width')

iris.corr()

sns.heatmap(iris.corr(), annot=True)

sns.boxplot(data=iris, y='sepal_length', x='species')

import matplotlib.pyplot as plt
x = [1,2,3,4,5,6]
y = [1,5,3,7,8,4]
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0,5,10)
y = np.exp(x) 
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0,5,10)
y = np.exp(x)
plt.yscale('log')
plt.plot(x,y)
plt.show()

fig = plt.figure()
import matplotlib.pyplot as plt
import numpy as np
x = np.random.randint(low=1,high=10,size=25)
plt.plot(x,color='aqua', linewidth=3, linestyle=':')
plt.show()
fig.savefig('lineplot.png')